"""add vehicle_assignments table

Revision ID: 3a377ccf5d4f
Revises: 764d7ad414d7
Create Date: 2026-07-14 11:42:10.655745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a377ccf5d4f'
down_revision: Union[str, Sequence[str], None] = '764d7ad414d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assignment_type', sa.Enum('DRIVER', 'FLEET_MANAGER', name='assignment_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='assignment_status'), nullable=False),
    sa.Column('odometer_out_km', sa.Integer(), nullable=True),
    sa.Column('odometer_in_km', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('unassigned_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('odometer_in_km IS NULL OR odometer_out_km IS NULL OR odometer_in_km >= odometer_out_km', name='ck_vehicle_assignments_odometer_in_gte_out'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unassigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_assignment_type'), 'vehicle_assignments', ['assignment_type'], unique=False)
    op.create_index('ix_vehicle_assignments_driver_one_vehicle', 'vehicle_assignments', ['user_id'], unique=True, postgresql_where=sa.text("assignment_type = 'DRIVER' AND status = 'ACTIVE' AND deleted_at IS NULL"))
    op.create_index(op.f('ix_vehicle_assignments_status'), 'vehicle_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_user_id'), 'vehicle_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_index('ix_vehicle_assignments_vehicle_type_active', 'vehicle_assignments', ['vehicle_id', 'assignment_type'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_assignments_vehicle_type_active', table_name='vehicle_assignments', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_user_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_status'), table_name='vehicle_assignments')
    op.drop_index('ix_vehicle_assignments_driver_one_vehicle', table_name='vehicle_assignments', postgresql_where=sa.text("assignment_type = 'driver' AND status = 'active' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_vehicle_assignments_assignment_type'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    # ### end Alembic commands ###
