"""initial migration

Revision ID: 52f2d538c0cc
Revises: 
Create Date: 2026-07-08 20:43:44.597245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52f2d538c0cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parts_sku', table_name='parts')
    op.drop_table('parts')
    op.drop_table('fuel_logs')
    op.drop_table('odometer_logs')
    op.drop_table('insurance_policies')
    op.drop_table('maintenance_records')
    op.drop_table('contracts')
    op.drop_table('alerts')
    op.drop_index('ix_vehicles_license_plate', table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vin', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fuel_type', postgresql.ENUM('petrol', 'diesel', 'electric', 'hybrid', 'lpg', 'cng', name='fueltype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'in_maintenance', 'out_of_service', 'reserved', name='vehiclestatus'), autoincrement=False, nullable=False),
    sa.Column('odometer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name='vehicles_driver_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey'),
    sa.UniqueConstraint('vin', name='vehicles_vin_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_vehicles_license_plate', 'vehicles', ['license_plate'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('alert_type', postgresql.ENUM('contract_expiry', 'insurance_expiry', 'maintenance_due', 'license_expiry', 'service_due', 'low_stock', name='alerttype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_dismissed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='alerts_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='alerts_pkey')
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contract_type', postgresql.ENUM('purchase', 'lease', 'rental', name='contracttype'), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('monthly_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('max_km', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='contracts_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contracts_pkey')
    )
    op.create_table('part_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('part_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('maintenance_record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fulfilled_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'fulfilled', 'rejected', 'cancelled', name='partrequeststatus'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fulfilled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='part_requests_approved_by_fkey'),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.id'], name='part_requests_fulfilled_by_fkey'),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], name='part_requests_maintenance_record_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name='part_requests_part_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='part_requests_requested_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='part_requests_pkey')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('technician_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('maintenance_type', postgresql.ENUM('preventive', 'corrective', 'inspection', 'tire', 'oil_change', 'other', name='maintenancetype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'in_progress', 'completed', 'cancelled', name='maintenancestatus'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('odometer_at_service', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('next_service_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('next_service_km', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name='maintenance_records_technician_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='maintenance_records_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='maintenance_records_pkey')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('policy_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('insurer', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('coverage_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('premium', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='insurance_policies_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='insurance_policies_pkey')
    )
    op.create_table('odometer_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='odometer_logs_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='odometer_logs_pkey')
    )
    op.create_table('fuel_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('logged_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('log_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('liters', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('cost_per_liter', sa.NUMERIC(precision=8, scale=3), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('odometer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], name='fuel_logs_logged_by_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='fuel_logs_vehicle_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fuel_logs_pkey')
    )
    op.create_table('parts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('quantity_on_hand', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reorder_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='parts_pkey')
    )
    op.create_index('ix_parts_sku', 'parts', ['sku'], unique=True)
    # ### end Alembic commands ###
