"""create table maintenance_work_orders

Revision ID: 6be926a3a9bd
Revises: e8350be24055
Create Date: 2026-08-07 11:40:53.668087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be926a3a9bd'
down_revision: Union[str, Sequence[str], None] = 'e8350be24055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_no', sa.String(length=30), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('workshop_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('maintenance_type', sa.Enum('preventive', 'corrective', 'inspection', 'emergency', name='maintenancetype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'critical', name='maintenancepriority'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'in_progress', 'completed', 'closed', 'cancelled', name='maintenanceworkorderstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odometer_at_service_km', sa.Integer(), nullable=True),
    sa.Column('total_labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_parts_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_index(op.f('ix_maintenance_work_orders_deleted_at'), 'maintenance_work_orders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_scheduled_date'), 'maintenance_work_orders', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_started_at'), 'maintenance_work_orders', ['started_at'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_status'), 'maintenance_work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_vehicle_id'), 'maintenance_work_orders', ['vehicle_id'], unique=False)
    op.create_index('ix_maintenance_work_orders_vehicle_status', 'maintenance_work_orders', ['vehicle_id', 'status'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_workshop_id'), 'maintenance_work_orders', ['workshop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_work_orders_workshop_id'), table_name='maintenance_work_orders')
    op.drop_index('ix_maintenance_work_orders_vehicle_status', table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_vehicle_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_status'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_started_at'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_scheduled_date'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_deleted_at'), table_name='maintenance_work_orders')
    op.drop_table('maintenance_work_orders')
    # ### end Alembic commands ###
