"""add vehicle table

Revision ID: 764d7ad414d7
Revises: b999cc621417
Create Date: 2026-07-11 14:32:25.441059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764d7ad414d7'
down_revision: Union[str, Sequence[str], None] = 'b999cc621417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'IN_MAINTENANCE', 'OUT_OF_SERVICE', 'RETIRED', name='vehicle_status'), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vehicle_model_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicles_license_plate_active', 'vehicles', ['license_plate'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND license_plate IS NOT NULL'))
    op.create_index('ix_vehicles_vin_active', 'vehicles', ['vin'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('vehicle_tags',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vehicle_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_tags')
    op.drop_index('ix_vehicles_vin_active', table_name='vehicles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_vehicles_license_plate_active', table_name='vehicles', postgresql_where=sa.text('deleted_at IS NULL AND license_plate IS NOT NULL'))
    op.drop_table('vehicles')
    op.drop_table('tags')
    # ### end Alembic commands ###
