"""
Seed script for the manufacturers table.

Usage:
    python -m app.seeds.manufacturers
"""

import asyncio

from sqlalchemy import text
from sqlalchemy.dialects.postgresql import insert as pg_insert

from app.core.database import AsyncSessionLocal
from app.models.manufacturer import Manufacturer

MANUFACTURER_NAMES = [
    # Mainstream global
    "Toyota",
    "Volkswagen",
    "Ford",
    "General Motors",
    "Honda",
    "Nissan",
    "Hyundai",
    "Kia",
    "Stellantis",
    "Renault",
    "Suzuki",
    "Mazda",
    "Subaru",
    "Mitsubishi",
    "Chevrolet",
    "GMC",
    "Buick",
    "Cadillac",
    "Chrysler",
    "Dodge",
    "Jeep",
    "Ram",
    "Lincoln",
    "Peugeot",
    "Citroën",
    "Opel",
    "Vauxhall",
    "Fiat",
    "Alfa Romeo",
    "Lancia",
    "Seat",
    "Škoda",
    "Dacia",
    "Daihatsu",
    "Isuzu",
    "Mahindra",
    "Tata Motors",
    "Maruti Suzuki",
    "Great Wall Motors",
    "Geely",
    "BYD",
    "Chery",
    "SAIC Motor",
    "Changan",
    "GAC Group",
    "Dongfeng",
    "FAW Group",
    "Haval",
    "MG Motor",
    "Wuling",
    "Proton",
    "Perodua",
    # Luxury / premium
    "Mercedes-Benz",
    "BMW",
    "Audi",
    "Porsche",
    "Lexus",
    "Infiniti",
    "Acura",
    "Volvo",
    "Jaguar",
    "Land Rover",
    "Genesis",
    "Maserati",
    "Bentley",
    "Rolls-Royce",
    "Aston Martin",
    "Ferrari",
    "Lamborghini",
    "Bugatti",
    "McLaren",
    "Pagani",
    "Koenigsegg",
    "Rimac",
    # EV / startups
    "Tesla",
    "Rivian",
    "Lucid Motors",
    "Polestar",
    "NIO",
    "XPeng",
    "Li Auto",
    "Fisker",
    "Faraday Future",
    "Vinfast",
    "Canoo",
    "Lordstown Motors",
    "Nikola",
    "Zeekr",
    "Aiways",
    "Karma Automotive",
    "Arrival",
    "Lightyear",
    "Sono Motors",
    # Trucks / commercial / off-highway
    "Volvo Trucks",
    "Scania",
    "MAN",
    "Iveco",
    "DAF Trucks",
    "Freightliner",
    "Kenworth",
    "Peterbilt",
    "Mack Trucks",
    "Navistar International",
    "Hino Motors",
    "UD Trucks",
    "Foton Motor",
    "Sinotruk",
    "Western Star",
    "Oshkosh Corporation",
    "Caterpillar",
    "JCB",
    # Motorcycle / powersports (many also make cars/ATVs)
    "Harley-Davidson",
    "Ducati",
    "Yamaha Motor",
    "Kawasaki Heavy Industries",
    "Triumph Motorcycles",
    "KTM",
    "Royal Enfield",
    "Piaggio",
    "Aprilia",
    "Vespa",
    "Polaris Industries",
    "Can-Am",
    "Arctic Cat",
    "Ski-Doo",
    # Historic / defunct but notable marques
    "Studebaker",
    "Packard",
    "Hudson Motor Car Company",
    "Nash Motors",
    "AMC",
    "Pontiac",
    "Oldsmobile",
    "Mercury",
    "Saturn Corporation",
    "Plymouth",
    "DeLorean Motor Company",
    "Duesenberg",
    "Auburn Automobile",
    "Cord Automobile",
    "Tucker Corporation",
    "Checker Motors",
    "DKW",
    "NSU Motorenwerke",
    "Borgward",
    "Wartburg",
    "Trabant",
    "Simca",
    "Talbot",
    "Panhard",
    "Delahaye",
    "Bugatti Automobiles (1909)",
    "Hispano-Suiza",
    "Isotta Fraschini",
    "Lagonda",
    "Riley Motor",
    "Wolseley Motors",
    "Austin Motor Company",
    "Morris Motors",
    "Triumph Motor Company",
    "Rover Company",
    "Standard Motor Company",
    "Hillman",
    "Humber",
    "Singer Motors",
    "Jowett",
    "Armstrong Siddeley",
    "Daimler Company",
    "Alvis",
    "AC Cars",
    "Lotus Cars",
    "TVR",
    "Marcos Engineering",
    "Reliant Motor Company",
    "Ginetta",
    "Caterham Cars",
    "Noble Automotive",
    "Ariel Motor Company",
    # Asian legacy / niche
    "Datsun",
    "Daewoo Motors",
    "Ssangyong Motor",
    "Asia Motors",
    "Honda Motorcycle & Scooter",
    "Mitsuoka Motor",
    "Autozam",
    "Hino Diesel",
    "Nissan Diesel",
    "Kawasaki Motors",
    # European niche / coachbuilders / performance
    "Spyker Cars",
    "Donkervoort",
    "Wiesmann",
    "Gumpert",
    "Melkus",
    "Abarth",
    "De Tomaso",
    "Zagato",
    "Pininfarina",
    "Italdesign",
    "Bertone",
    "Ghia",
    "Vignale",
    # Indian / other emerging markets
    "Force Motors",
    "Ashok Leyland",
    "Bajaj Auto",
    "TVS Motor Company",
    "Hero MotoCorp",
    "Premier Automobiles",
    "Hindustan Motors",
    # Australian / other regional
    "Holden",
    "Ford Australia",
    "GAZ Group",
    "AvtoVAZ (Lada)",
    "UAZ",
    "Moskvitch",
    # Additional current-market and regional brands to round out the list
    "Toyota Daihatsu Engineering",
    "Suzuki Motorcycle",
    "Yulon Motor",
    "Luxgen",
    "Proton Holdings",
    "DFSK",
    "JAC Motors",
    "Baic Group",
    "Hongqi",
    "Wey Motor",
    "Ora (Great Wall EV)",
    "Denza",
    "Voyah",
    "Avatr Technology",
    "IM Motors",
    "Neta Auto",
    "Leapmotor",
    "Skywell",
    "Enovate",
    "Human Horizons (HiPhi)",
]

MANUFACTURER_NAMES = MANUFACTURER_NAMES[:200]


async def seed_manufacturers() -> None:
    async with AsyncSessionLocal() as session:
        stmt = pg_insert(Manufacturer).values(
            [{"name": name, "is_active": True} for name in MANUFACTURER_NAMES]
        )
        stmt = stmt.on_conflict_do_nothing(
            index_elements=["name"],
            index_where=text("deleted_at IS NULL"),
        )
        await session.execute(stmt)
        await session.commit()

    print(f"Seeded {len(MANUFACTURER_NAMES)} manufacturers (duplicates skipped).")


if __name__ == "__main__":
    asyncio.run(seed_manufacturers())
